Cleanup script for removing all instances and disks in the cloud
theforeman/foreman_google pull request #33
Opened 2022-05-23 14:57 UTC by stejskalleos

2022-05-24 07:51 UTC, adamruzicka commented
Just to make sure I'm reading this right, the intent of the script is to remove *everything*, correct?

2022-05-24 09:53 UTC, stejskalleos commented
> Just to make sure I'm reading this right, the intent of the script is to remove _everything_, correct?

Yop, sometimes I forgot to remove all the instances (and their disks) I created during the day and then the billing is going up faster than I want to.

Plus it's way faster than the Google's UI.

2022-05-24 11:11 UTC, adamruzicka commented
Needs a rebase now

2022-05-24 11:17 UTC, adamruzicka requested changes

2022-05-24 11:17 UTC, adamruzicka commented on scripts/cleanup_cloud.rb
> +  client.delete_instance(zone, instance.name)
It feels like deletion of an instance is an asynchronous operation and disk removal may fail if the instance removal is not fully finished yet.

```
$ bundle exec ruby scripts/cleanup_cloud.rb  /home/aruzicka/Downloads/noted-terra-303613-69ae49292458.json     us-central1-a
Found instances:
>>> Deleting instance-1 instance

Found disks:
>>> Deleting disk-1 disk
Traceback (most recent call last):
        17: from scripts/cleanup_cloud.rb:30:in `<main>'
        16: from scripts/cleanup_cloud.rb:30:in `each'
        15: from scripts/cleanup_cloud.rb:32:in `block in <main>'
        14: from /home/aruzicka/vcs/foreman/foreman-google/app/lib/foreman_google/google_compute_adapter.rb:76:in `delete_disk'
        13: from /home/aruzicka/vcs/foreman/foreman-google/app/lib/foreman_google/google_compute_adapter.rb:115:in `delete'
        12: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/google-cloud-compute-v1-1.3.0/lib/google/cloud/compute/v1/disks/rest/client.rb:469:in `delete'
        11: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/google-cloud-compute-v1-1.3.0/lib/google/cloud/compute/v1/disks/rest/service_stub.rb:202:in `delete'
        10: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/gapic-common-0.9.0/lib/gapic/rest/client_stub.rb:76:in `make_delete_request'
         9: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/gapic-common-0.9.0/lib/gapic/rest/client_stub.rb:129:in `make_http_request'
         8: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/faraday-1.10.0/lib/faraday/connection.rb:200:in `delete'
         7: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/faraday-1.10.0/lib/faraday/connection.rb:516:in `run_request'
         6: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/faraday-1.10.0/lib/faraday/rack_builder.rb:154:in `build_response'
         5: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/gapic-common-0.9.0/lib/gapic/rest/faraday_middleware.rb:38:in `call'
         4: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/faraday-retry-1.0.3/lib/faraday/retry/middleware.rb:140:in `call'
         3: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/faraday-1.10.0/lib/faraday/middleware.rb:18:in `call'
         2: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/faraday-1.10.0/lib/faraday/response.rb:61:in `on_complete'
         1: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/faraday-1.10.0/lib/faraday/middleware.rb:19:in `block in call'
/home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/faraday-1.10.0/lib/faraday/response/raise_error.rb:16:in `on_complete': the server responded with status 400 (Faraday::BadRequestError)
        6: from scripts/cleanup_cloud.rb:30:in `<main>'
        5: from scripts/cleanup_cloud.rb:30:in `each'
        4: from scripts/cleanup_cloud.rb:32:in `block in <main>'
        3: from /home/aruzicka/vcs/foreman/foreman-google/app/lib/foreman_google/google_compute_adapter.rb:76:in `delete_disk'
        2: from /home/aruzicka/vcs/foreman/foreman-google/app/lib/foreman_google/google_compute_adapter.rb:115:in `delete'
        1: from /home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/google-cloud-compute-v1-1.3.0/lib/google/cloud/compute/v1/disks/rest/client.rb:446:in `delete'
/home/aruzicka/.toolbox/f35/.rvm/gems/ruby-2.7.2/gems/google-cloud-compute-v1-1.3.0/lib/google/cloud/compute/v1/disks/rest/client.rb:484:in `rescue in delete': An error has occurred when making a REST request: The disk resource 'projects/noted-terra-303613/zones/us-central1-a/disks/disk-1' is already being used by 'projects/noted-terra-303613/zones/us-central1-a/instances/instance-1' (Google::Cloud::InvalidArgumentError)
        5: from scripts/cleanup_cloud.rb:30:in `<main>'
        4: from scripts/cleanup_cloud.rb:30:in `each'
        3: from scripts/cleanup_cloud.rb:32:in `block in <main>'
        2: from /home/aruzicka/vcs/foreman/foreman-google/app/lib/foreman_google/google_compute_adapter.rb:76:in `delete_disk'
        1: from /home/aruzicka/vcs/foreman/foreman-google/app/lib/foreman_google/google_compute_adapter.rb:114:in `delete'
/home/aruzicka/vcs/foreman/foreman-google/app/lib/foreman_google/google_compute_adapter.rb:117:in `rescue in delete': uninitialized constant ForemanGoogle::GoogleComputeAdapter::Foreman (NameError)
```

+ the name error is something we should address

2022-05-25 12:54 UTC, stejskalleos commented on app/lib/foreman_google/google_compute_adapter.rb
> +    def delete_instance(zone, instance_identity)
`delete_instance` and `disks` are  not used anymore by the cleanup_script but they'll be useful later in follow up PRs

2022-05-26 08:38 UTC, adamruzicka reviewed
The asynchronous nature of removal still remains unaddressed. The error is nicer now, but I still have to run the script, wait for a minute or two and then run it again to really remove everything.

```shell
# bundle exec ruby scripts/cleanup_cloud.rb /home/aruzicka/Downloads/noted-terra-303613-69ae49292458.json us-central1-a
Deleting instances:
>>> Deleting instance-1 instance

Deleting disks:
>>> Deleting disk-1 disk
ERROR: An error has occurred when making a REST request: The disk resource 'projects/noted-terra-303613/zones/us-central1-a/disks/disk-1' is already being used by 'projects/noted-terra-303613/zones/us-central1-a/instances/instance-1'
>>> Deleting instance-1 disk
ERROR: An error has occurred when making a REST request: The disk resource 'projects/noted-terra-303613/zones/us-central1-a/disks/instance-1' is already being used by 'projects/noted-terra-303613/zones/us-central1-a/instances/instance-1'

Done.
```

2022-06-29 06:25 UTC, closed without merging